# Ian Braudaway
# makefile for lexer

OPTS = -Wall -Wextra -std=c99 -g -c
LOPTS = -Wall -Wextra -std=c99 -g
CC = gcc

types.o : types.c types.h
    $(CC) $(OPTS) types.c

lexeme.o : lexeme.c lexeme.h
    $(CC) $(OPTS) lexeme.c

lexer.o : lexer.c lexer.h
    $(CC) $(OPTS) lexer.c

scanner.o : scanner.c scanner.h
    $(CC) $(OPTS) scanner.c

clean : rm -f ./types ./lexeme ./lexer ./scanner

scanner : 

test1 :

test2 :

test3 :

test4 :

test5 :